Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -31,13 +31,16 @@ jobs:
         pip list
     - name: Unit Tests
       run: |
-        make test-unit
+        pytest -m "unit_tests" -o log_cli=true -o log_cli_level=INFO
     - name: Lint Tests
       run: |
-        make lint
+        isort --check cars tests
+        black --check cars tests
+        flake8 cars tests
+        pylint cars tests --rcfile=.pylintrc --output-format=parseable | tee pylint-report.txt # pipefail to propagate pylint exit code in bash
     - name: Notebooks Tests
       run: |
-        make test-notebook 
+        pytest -m "notebook_tests" -o log_cli=true -o log_cli_level=INFO
     - name: End2end Tests
       run: |
-        make test-end2end
+        pytest -m "end2end_tests" -o log_cli=true -o log_cli_level=INFO
